<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <RootNamespace>AdvancedAudioControls.SMTC</RootNamespace>
    <AssemblyName>AdvancedAudioControls.SMTC</AssemblyName>
    <Description>API .NET pour le module System Media Transport Controls (SMTC) de Windows.</Description>
  </PropertyGroup>

  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

</Project>
